### ISSUE TITLE
Host scanner

### ISSUE THREAD

**Issue by kostadin24** [osociety/network_tools#66] opened 2022-09-21 09:30 UTC
Can we have MAC address of host?
Since code is pinging IP address, this info can be retrieved also.

**Comment by git-elliot** [comment] 2022-09-21 13:56
Duplicate of https://github.com/osociety/network_tools/issues/7

**Closed** 2022-09-21 13:59 UTC
Labels: duplicate

**Comment by guyluz11** [comment] 2022-09-22 07:51
Also ping does not retrieve Mac address.

https://stackoverflow.com/questions/40430423/does-a-ping-response-contain-mac-address#:~:text=Ping%20does%20not%20reveal%20the,on%20windows%20to%20do%20that.

> Ping does not reveal the MAC address. It simply tells you if a server is online or not. You can use "nbtstat -a ip" command on windows to do that.

**Comment by kostadin24** [comment] 2022-09-22 19:14
Ping fills ARP table in device. Then call arp fo the job. But it is not
available after android 10. Also not available for iOS
